.\"	$OpenBSD$
.\"
.\" Copyright (c) 2018 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt ORT-XLIFF 1
.Os
.Sh NAME
.Nm ort-xliff
.Nd extract and merge translatable strings from ort configurations
.Sh SYNOPSIS
.Nm ort-xliff
.Op Fl c
.Fl j
.Ar config
.Op Ar xliff
.Nm ort-xliff
.Op Fl c
.Fl j
.Op Ar config...
.Fl x
.Op Ar xliff...
.Nm ort-xliff
.Op Fl c
.Fl u
.Ar config
.Op Ar xliff
.Nm ort-xliff
.Op Fl c
.Fl u
.Op Ar config...
.Fl x
.Op Ar xliff
.Nm ort-xliff
.Op Fl c
.Op Ar config...
.Sh DESCRIPTION
The
.Nm
utility accepts
.Xr ort 5
.Ar config
files, defaulting to standard input,
and extracts, merges, and updates translatable strings.
The translated strings are used only by
.Xr ort-javascript 1 .
The arguments are as follows:
.Bl -tag -width Ds
.It Fl c
Instead of creating an empty target when extracting strings, joining
translation, or updating with new translations, fill in the target with
the source.
.It Fl j
Merges one or more
.Ar xliff
files with an untranslated
.Ar config ,
producing another configuration on standard output containing the
translated strings.
.It Fl u
Update the
.Ar xliff
file with new translation labels found in
.Ar config .
The updated translations are emitted on standard output.
.It Ar xliff
An XLIFF 1.2 file containing translated strings.
.It Ar config
A
.Xr ort 5
configuration file.
There may be multiple files in a single configuration.
.El
.Pp
By default,
.Nm
outputs all translatable labels onto standard output.
.Pp
When invoked with
.Fl j
or
.Fl u ,
multiple
.Xr ort 5
configuration files and XLIFF files as arguments must be broken up by
the
.Fl x
flag, which signals the beginning of the XLIFF files.
.Pp
Translatable content in
.Xr ort 5
is limited to
.Cm jslabel
phrases for enumerations and bitfields.
.Pp
The usual usage sequence is as follows:
.Bl -enum
.It
Extract translatable content from a
.Xr ort 5
configuration into an XLIFF file.
.It
Give the XLIFF file a target language and translate the strings.
.It
Merge the XLIFF file back into the original
.Xr ort 5
with
.Fl j .
Already-translated labels for the given language are not overriden by
default.
.It
Use the produced configuration for further use in
.Xr ort-javascript 1 .
.El
.Pp
With these steps, integral enumeration values produced by the JSON
output of
.Xr ort-c-source 1
and
.Xr ort-c-header 1
may be translated into human-readable, language-specific labels.
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Take a dummy configuration
.Pa foo.kwbp
containing the following:
.Bd -literal
enum foo {
  item bar 0 jslabel "bar";
  item foo 1 jslabel "foo";
};
.Ed
.Pp
Begin by extracting translatable strings from the input.
.Bd -literal
% ort-xliff foo.kwbp
<xliff version="1.2">
  <file target-language="TODO" tool="ort-xliff">
    <body>
      <trans-unit id="1">
        <source>bar</source>
      </trans-unit>
      <trans-unit id="2">
        <source>foo</source>
      </trans-unit>
    </body>
  </file>
</xliff>
.Ed
.Pp
Change the language into something useful, such as
.Qq fr ,
and translate the strings into
.Qq le bar
and
.Qq le foo ,
respectively.
Then join the output,
.Pa foo.fr.xliff ,
with the input configuration.
.Bd -literal
% ort-xliff -j foo.kwbp foo.fr.xliff
enum foo {
  item bar 0
    jslabel "bar"
    jslabel.fr "le bar";
  item foo 1
    jslabel "foo"
    jslabel.fr "le foo";
};
.Ed
.Pp
This output file can then be used with
.Xr ort-javascript 1
to have per-language label filling.
.Pp
Multiple configuration files, when joining, may also be specified.
.Bd -literal
% ort-xliff -j foo1.kwbp foo2.kwbp -x foo.fr.xliff
.Ed
.Pp
The configuration or XLIFF files may also be passed on standard input by
omitting the file.
In the first case, the configuration is omitted.
(The special
.Dq \&--
is used to prevent
.Fl x
from being interpreted as a command-line option.)
In the second case, it's the translation file.
.Bd -literal
% ort-xliff -j -- -x foo.fr.xliff < foo.kwbp
% ort-xliff -j foo1.kwbp foo2.kwbp -x < foo.xliff
.Ed
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr ort-javascript 1 ,
.Xr ort 5
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
