/*	$Id$ */
/*
 * Copyright (c) 2017 Kristaps Dzonsons <kristaps@bsd.lv>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#include "config.h"

#include <sys/queue.h>

#include <assert.h>
#include <ctype.h>
#if HAVE_ERR
# include <err.h>
#endif
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "extern.h"

static	const char *const puttypes[FTYPE__MAX] = {
	"kjson_putintp", /* FTYPE_INT */
	"kjson_putdoublep", /* FTYPE_REAL */
	NULL, /* FTYPE_BLOB (XXX: is special) */
	"kjson_putstringp", /* FTYPE_TEXT */
	NULL, /* FTYPE_PASSWORD (don't print) */
	NULL, /* FTYPE_STRUCT */
};

static void
gen_func_obj(const struct strct *p)
{

	print_func_json_obj(p, 0);
	puts("\n"
	     "{");
	printf("\tkjson_objp_open(r, \"%s\");\n"
	       "\tjson_%s_data(r, p);\n", p->name, p->name);
	puts("\tkjson_objp_close(r);\n"
	     "}\n"
	     "");
}

static void
gen_func_data(const struct strct *p)
{
	const struct field *f;

	print_func_json_data(p, 0);
	puts("\n"
	     "{");
	TAILQ_FOREACH(f, &p->fq, entries) {
		if (FTYPE_STRUCT == f->type)
			printf("\tjson_%s_obj(r, p->%s);\n",
				f->ref->tstrct, f->name);
		if (NULL == puttypes[f->type])
			continue;
		printf("\t%s(r, \"%s\", p->%s);\n", 
			puttypes[f->type], f->name, f->name);
	}
	puts("}\n"
	     "");
}

void
gen_json_source(const struct strctq *q, const char *header)
{
	const struct strct *p;

	print_commentt(0, COMMENT_C, 
		"WARNING: automatically generated by "
		"kwebapp " VERSION ".\n"
		"DO NOT EDIT!");

	/* Start with all headers we'll need. */

	printf("#include <sys/queue.h>\n"
	       "\n"
	       "#include <stdio.h>\n"
	       "#include <stdlib.h>\n"
	       "#include <string.h>\n"
	       "#include <unistd.h>\n"
	       "\n"
	       "#include <kcgijson.h>\n"
	       "\n"
	       "#include \"%s\"\n"
	       "\n",
	       header);

	TAILQ_FOREACH(p, q, entries)
		gen_func_data(p);
	TAILQ_FOREACH(p, q, entries)
		gen_func_obj(p);
}
