.\"	$OpenBSD: mdoc.template,v 1.15 2014/03/31 00:09:54 dlg Exp $
.\"
.\" Copyright (c) 2017 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 1 2017 $
.Dt KWEBAPP 5
.Os
.Sh NAME
.Nm kwebapp
.Nd syntax for kwebapp configuration
.Sh DESCRIPTION
The
.Nm
configuration is used by
.Xr kwebapp 1
to generate C source and header files that drive a database.
It is a free-form (white-space is not significant beyond separating
tokens) configuration language with the following rough structure:
.Bd -literal -offset indent
[ "struct" structname 
  "{"
    [ "field" fieldname [ type [ typeinfo ] ] ";" ]+
    [ "comment" quoted_string ";" ]?
  "}"
]+
.Ed
.Pp
In simple language, one or more structure definitions, each containing
one or more fields.
A structure is a database table or C struct; whereas a field is a column
or a struct member.
The names of structures and fields must be unique case-insensitive
alphanumeric strings starting with a letter.
In
.Nm ,
these are collectively called
.Dq objects .
.Ss Structures
A structure object defines a C structure or a database table.
Its definition begins with the word
.Cm struct ,
then the name of the structure, then a set of one or more
.Cm fields
within the curly braces.
.Bd -literal -offset indent
"struct" structname "{" [ fields ]+ "}"
.Ed
.Pp
Structures may be mapped into by other structures from referencing
fields, which are similar to foreign keys.
In SQL terms, this abstracts the notion of inner joins on foreign keys.
.Ss Fields
A field object defines a C structure member and/or a database column.
Each field consists of the word
.Cm field
followed by a field
.Cm name
and
.Cm type ,
then additional information.
.Bd -literal -offset indent
"field" [name | name:target] type [typeinfo]+ ";" 
.Ed
.Pp
The
.Cm name
may either be a standalone identifier or a
.Dq foreign key
referencing a field in another structure.
The
.Cm type
may be one of
.Cm struct ,
.Cm int ,
or
.Cm text .
The latter two are
.Dq native
types mapping into 64-bit integers and character strings, respectively.
The former has the full syntax of
.Pp
.Dl \(dqstruct\(dq source:struct.field
.Pp
This special type joins the field
.Cm source
to the target structure and field
.Cm struct.field .
This special type differs from native type foreign keys in that it will
be joined on database queries, while the native type is merely part of
the definition.
It is an error for a
.Cm struct
and native foreign key to reference different target fields.
.Pp
The
.Cm typeinfo
may consist of the following:
.Bd -literal -offset indent
"rowid" | "comment" quoted_string
.Ed
.Pp
The
.Cm rowid
means (in SQL terms) that the field is a primary key.
This is only available for the
.Cm int
type.
The quoted comment string documents the field.
.Ss Comments
Each
.Nm
object may be documented.
This documentation is reflected in the generated sources.
For the time being, documentation may be considered opaque text that may
not contain a double-quote character unless preceded by a backslash.
(The backslash is removed in output.)
.Pp
For the time being, white-space is handled by retaining the first
instance, then stripping subsequent white-space.
This might change.
.Sh EXAMPLES
A simple session table is as follows:
.Bd -literal
struct user {
  field name text;
  field id int rowid;
  comment "A regular user.";
}

struct session { 
  field user struct userid:user.id;
  field userid comment "Associated user.";
  field altuserid:user.id;
  field token comment "Random cookie.";
  field id int rowid;
  comment "Authenticated session.";
}
.Ed
.Pp
This generates two C structures,
.Li user
and
.Li session ,
consisting of the given fields.
The
.Li session
structure contains a
.Li struct user
as well; thus, there is a declarative order that
.Xr kwebapp 1
enforces when writing out structures.
.Pp
The SQL interface, when fetching a
.Li struct session ,
will employ an
.Li INNER JOIN
over the user identifier and session
.Li userid
field.
.Sh SEE ALSO
.Xr kwebapp 1
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
