.\"	$OpenBSD$
.\"
.\" Copyright (c) 2017, 2018 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt KWEBAPP-JAVASCRIPT 1
.Os
.Sh NAME
.Nm kwebapp-javascript
.Nd implement web application JavaScript and TypeScript classes
.Sh SYNOPSIS
.Nm kwebapp-javascript
.Op Fl t
.Op Ar config...
.Sh DESCRIPTION
The
.Nm
utility accepts a
.Xr kwebapp 5
.Ar config
.Pq defaulting to standard input
and creates JavaScript or TypeScript classes formatting the JSON
produced by
.Xr kwebapp-c-header 1
and
.Xr kwebapp-c-source 1 .
The configuration may be broken apart into several files.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl t
Emits Typescript instead of JavaScript.
.It Ar config
Configuration file in
.Xr kwebapp 5
syntax.
.El
.Pp
Both output formats consist of a set of classes within the
.Qq kwebapp
namespace describing structures, enumerations, and bitfields.
The method for acquiring the JSON is not managed by
.Nm ,
but is usually provided by a CGI interfacing with
.Xr kwebapp-c-header 1
and
.Xr kwebapp-c-source 1 .
.Pp
To use the interface, simply include the generated file as a script,
create objects from the JSON exported by
.Xr kwebapp-c-source 1 ,
and invoke the applicable object's
.Fn fill ,
.Fn fillInner ,
and
.Fn fillArray
methods with a DOM tree node.
.Pp
These methods operate on elements with certain classes beneath a given
element root as follows:
.Bl -tag -width Ds
.It Li foo-xxxx-bits-checked
Sets or unsets the
.Li checked
attribute depending upon whether the input's
.Li value
attribute is covered by the object's bitmask.
Only applicable to bit types.
.It Li foo-xxxx-date-text
Replaces the contents of the element with the ISO 8601 date of the
object's value.
Only applicable to date and epoch types.
.It Li foo-xxxx-date-value
Sets the
.Li value
attribute to the ISO 8601 date of the object's value.
Only applicable to date and epoch types.
.It Li foo-xxxx-enum-select
All
.Li <option>
descendents of the element are marked as
.Qq selected
or not depending upon whether their value matches the field value.
.It Li foo-xxxx-obj
For structures, creates and invokes the
.Fn fillInner
method on the nested structure at the given element and its descendents.
This is only applicable for structure types.
.It Li foo-xxxx-text
Replaces the contents of the element with the field value.
This is not applicable to blob native types.
.It Li foo-xxxx-value
Sets the
.Li value
attribute (as in a form submission) with the field value.
This is not applicable to blob native types.
.It Li foo-xxxx-value-checked
Sets or unsets the
.Li checked
attribute depending upon whether the input's
.Li value
attribute matches the objects.
This is not applicable to blob or structure types.
.It Li foo-has-xxxx
Remove the
.Dq hide
class if the object is null, otherwise add the
.Dq hide
class.
.It Li foo-no-xxxx
Add the
.Dq hide
class if the object is null, otherwise remove the
.Dq hide
class.
.El
.Pp
The
.Fn fillInner
method may be used to exclude the passed-in element, while
.Fn fill
includes this element.
.Pp
The
.Fn fillArray
method invokes
.Fn fill
repeatedly over an array of objects by removing, then subsequently
cloning and appending, the first element of the give DOM root.
.Pp
Enumeration and bitfield classes are also generated from the input file.
These are appended to the namespace as a series of classes
consisting of static variables assigned the enumeration value.
.Pp
All output objects are fully documented in the
.Xr jsdoc 1
format.
.Ss Customisation
All functions accept an optional argument for providing custom per-field
or per-structure callbacks.
Keys in the object must consist of the structure name, followed by a
dash, followed by the field name.
For example, assuming a structure
.Dq client
with a field
.Dq dob
consisting of a UNIX epoch:
.Bd -literal -offset indent
var custom = { 'client-dob': formatDate };
new kwebapp.client(obj).fillInner(document, custom);
.Ed
.Pp
And letting a formatting function be:
.Bd -literal -offset indent
function formatDate(e, name, value) {
  var list, i;
  list = e.getElementsByClassName('client-dob-date-moment');
  for (i = 0; i < list.length; i++)
    list[i].innerHTML =
      moment.unix(value).format('DD-MM-YYYY'));
}
.Ed
.Pp
This invokes the
.Dq moment.js
formatter to create dates.
.Pp
The same can be applied to structures instead of to fields within
structures.
The keys for these are simply the structure name.
.Bd -literal -offset indent
var custom = { 'client': formatClient };
new kwebapp.client(obj).fillInner(document, custom);
.Ed
.Pp
The callback will then be provided the full client object.
.Pp
In either case, the value for the custom key may also be an array of
functions just as above.
Each will be invoked in the order given, in the same way.
.Bd -literal -offset indent
var custom = { 'client': [ format1, format2 ] };
.Ed
.Pp
The callback function (or functions) will be invoked regardless of
whether the value has been set.
In the event of an unset field value, the function is passed
.Dv null .
.Pp
When using TypeScript, the values of the format function are typed
according to the structure or field passed.
For example, if the
.Dq dob
field of structure
.Dq client
is a UNIX epoch, the format function accepts a number or null.
.Bd -literal -offset indent
function formatDate(e: HTMLElement,
  name: string, v: number|null): void {
	/* Do something... */
}
.Ed
.Pp
The dictionary object is defined as follows:
.Bd -literal -offset indent
let custom: DataCallbacks = { 'client-dob': formatDate };
new kwebapp.client(obj).fillInner(document, custom);
.Ed
.Ss Enumeration and Bitfield Labels
Enumerations and bitfields in
.Xr kwebapp 5
are translated into classes with a static
.Fn format
function that may be passed as a custom handler for corresponding
fields.
These fill in the
.Xr kwebapp 5
.Cm jslabel
of the corresponding values.
If a language is specified in the root of the HTML or XML document, it
is first matched to the language of the label.
If there is no language, or none for that label, the default label is
used.
If there is no default label, an empty string is used instead.
.Pp
In the event of unset bitfields, the corresponding
.Xr kwebapp 5
.Cm isunset
value is used, and the
.Li kwbp-unset
class set on the element.
For null values,
.Cm isnull
is used and
.Li kwbp-null
set on the element.
.Pp
For example, to fill in the label of an enumeration
.Li enum someenum
on a field named
.Li val ,
provide a custom callback.
.Bd -literal -offset indent
var obj = JSON.parse(response);
var e = document.getElementById('foo');
var custom = {
  'foo-val': kwebapp.someenum.format
};
new kwebapp.foo(obj).fill(e, custom);
.Ed
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Given a
.Xr kwebapp 5
structure
.Dq foo
with a single field
.Dq bar
and an AJAX response
.Dq response ,
an example invocation may be as follows:
.Bd -literal -offset indent
var obj = JSON.parse(response);
var e = document.getElementById('foo');
new kwebapp.foo(obj).fill(e);
.Ed
.Pp
This will fill in all classes under
.Li e
named
.Li foo-bar-value ,
.Li foo-bar-text ,
.Li foo-has-bar ,
.Li foo-no-bar ,
and
.Li foo-enum-select .
.Pp
The TypeScript interface would intsead look as follows, assuming that
the JSON parse returns the
.Dq foo
JSON object.
.Bd -literal -offset indent
let obj: kwebapp.fooData =
  <kwebapp.fooData>JSON.parse(response);
let e: HTMLElement|null =
  document.getElementById('foo');
if (null !== e)
  new kwebapp.foo(obj).fill(e);
.Ed
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr jsdoc 1 ,
.Xr kwebapp-c-header 1 ,
.Xr kwebapp-c-source 1 ,
.Xr tsc 1 ,
.Xr kwebapp 5
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
