.\"	$OpenBSD$
.\"
.\" Copyright (c) 2017 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt KWEBAPP 1
.Os
.Sh NAME
.Nm kwebapp
.Nd create web application API and database layer
.Sh SYNOPSIS
.Nm kwebapp
.Op Fl hns
.Op Fl c Ar header
.Op Fl d Ar oldconfig
.Op Ar config
.Sh DESCRIPTION
The
.Nm
utility accepts a configuration file
.Ar config
.Pq defaulting to standard input
and creates source files defining a web application's C API to its
database.
It is a way of reducing the often-repeated code of serialising and
de-serialising simple structures from a database.
By default, it generates the C header file
.Pq see Fl h .
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl c Ar header
Create the
.Sx C source
file implementing the header file
.Ar header .
.It Fl d Ar oldconfig
Generate an
.Sx SQL update
sequence that updates
.Ar oldconfig ,
a
.Xr kwebapp 5
file, with the new configuration.
.It Fl h
Create the
.Sx C header
file.
.It Fl n
Parse only (dry-run).
.It Fl s
Create the full
.Sx SQL schema
file.
.It Ar config
A configuration file in the
.Xr kwebapp 5
format.
.El
.Pp
In all instances (except for
.Fl n ) ,
the generated file is produced on standard output.
.Ss C header
The C header file generated by
.Nm
lists all structures and functions defined by
.Ar config .
Sources including the header will also need
.In ksql.h
.Po
see
.Xr ksql 3
for details
.Pc
and
.In stdint.h .
.Pp
For each structure object in
.Ar config ,
.Nm
generates a C
.Dq struct
by that name containing all typed fields.
It also generates the following functions, taking
.Dq foo
to be the name of the structure object:
.Bl -tag -width Ds
.It Fn db_foo_free
Frees a pointer created by
.Fn db_foo_by_rowid
or a custom search.
.It Fn db_foo_fill
Zero and fill in a pointer from an open database query.
This fills all nested structures as well.
.It Fn db_foo_unfill
Release resources filled from a database query.
This frees all nested structures as well.
.It Fn db_foo_by_rowid
Fetch a record by its unique identifier.
Only valid for objects having a
.Cm rowid .
.It Fn db_foo_by_xxxx
If the structure object has any named searches, these are listed in
place of the
.Dq xxxx .
.It Fn db_foo_by__xxxx__yy_zz
If the structure has any anonymous searches, these are listed with an
undescore preceding each search term.
In the given example,
.Dq xxxx
is a field in the given structure and
.Dq yy_zz
means a field
.Dq zz
in the nested structure
.Dq yy .
.El
.Pp
All of these are fully documented in the header file.
The structures are documented using the comments given in
.Ar config .
.Ss C source
A series of function definitions for the
.Sx C header .
This is internally documented to assist the reader.
.Ss SQL schema
Emits a series of
.Cm CREATE TABLE
SQL commands representing the objects in
.Ar config .
These encapsulate the foreign keys and all other required SQL
attributes.
.Ss SQL update
Emits a series of
.Cm CREATE TABLE
and
.Cm ALTER TABLE
SQL commands to update the configuration
.Ar oldconfig
to the new configuration
.Ar config .
.Pp
The configuration files are considered incompatible if they contain
destructive differences: dropped objects (structures or fields) or
different fields (types, references, attributes).
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.Ex -std
.Pp
In the case of
.Fl d ,
exiting >0 means that
.Ar oldconfig
and
.Ar config
are incompatible.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kwebapp 5
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
