.\"	$OpenBSD$
.\"
.\" Copyright (c) 2017 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt KWEBAPP 1
.Os
.Sh NAME
.Nm kwebapp
.Nd test web application configuration syntax
.Sh SYNOPSIS
.Nm kwebapp
.Op Ar config
.Sh DESCRIPTION
The
.Nm
utility accepts a configuration file
.Ar config
.Pq defaulting to standard input
and tests the configuration syntax.
Warnings and errors, if any, are printed to standard error.
.Pp
For output, see the following:
.Bl -tag -width Ds
.It Xr kwebapp-c-header 1
Output the C API (declarations) describing a configuration.
The implementation may be produced by
.Xr kwebapp-c-source 1 .
.It Xr kwebapp-c-source 1
Output the C implementation (definitions) of the API produced by
.Xr kwebapp-c-header 1 .
.It Xr kwebapp-javascript 1
Output a series of classes for filling an HTML DOM tree with data
exported via the JSON interface optionally declared by
.Xr kwebapp-c-header 1
and implemented by
.Xr kwebapp-c-source 1 .
.It Xr kwebapp-sql 1
Output the SQL schema describing a configuration.
.It Xr kwebapp-sqldiff 1
Output a series of non-destructive SQL statements to change an existing
SQL schema (usually produced by
.Xr kwebapp-sql 1 )
into a new one.
This is used for updating schemas.
.El
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.Sh EXIT STATUS
.Ex -std
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr kwebapp 5
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
