.\"	$OpenBSD$
.\"
.\" Copyright (c) 2017, 2018 Kristaps Dzonsons <kristaps@bsd.lv>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt ORT-SQLDIFF 1
.Os
.Sh NAME
.Nm ort-sqldiff
.Nd produce ort SQL schema differences
.Sh SYNOPSIS
.Nm ort-sqldiff
.Op Fl d
.Op Ar oldconfig...
.Fl f
.Op Ar config...
.Nm ort-sqldiff
.Op Fl d
.Ar oldconfig
.Op Ar config
.Sh DESCRIPTION
The
.Nm
utility accepts
.Xr ort 5
configurations
.Ar config
and
.Ar oldconfig
and produces an SQL schema describing the configuration.
Its arguments are as follows:
.Bl -tag -width Ds
.It Fl d
Apply and allow some destructive changes.
See
.Sx Delete mode .
.El
.Pp
The new configuration is preceded by 
.Fl f .
In a special case for simplicity, a single old and new configuration may
be specified together without
.Fl f .
Either
.Ar oldconfig
or
.Ar config
may be empty, and thus read from standard input, but not both.
.Pp
.Nm
outputs a series of
.Cm CREATE TABLE
and
.Cm ALTER TABLE
SQL commands to update the configuration
.Ar oldconfig
to the new configuration
.Ar config .
In
.Sx Delete mode ,
.Cm DROP TABLE
SQL commands are also emitted.
(Dropped columns are noted, but not actually dropped.
This is a limitation of
.Xr sqlite3 1 . )
.Pp
The configuration files are considered incompatible if they contain
destructive differences: dropped objects (structures or fields) or
different fields (types, references, attributes).
.Pp
If fields are added to a structure (columns to a table), the
.Cm default
statement is used for generating an SQL default value.
If a
.Cm default
statement is not provided for columns
.Cm NOT NULL ,
the update will fail as-is and must be manually edited with default
values.
.Pp
It's good practise, but not enforced by
.Nm ,
to wrap the edit script in a transaction.
.Bd -literal
% ( echo "BEGIN EXCLUSIVE TRANSACTION ;" \e
    ort-sqldiff old.kwbp new.kwbp ; \e
    echo "COMMIT TRANSACTION ;" ) | sqlite3 foo.db
.Ed
.Pp
There is no additional processing in the database edit script: if the
script is run twice, it will attempt to create tables and modify columns
twice.
.Pp
The SQL generated is designed for
.Xr sqlite3 1 .
.Ss Delete mode
When
.Fl d
has been specified,
.Nm
destructive changes are allowed.
These consist of the following:
.Bl -bullet
.It
dropped enumerations and bitfields
.It
dropped enumeration and bitfield items
.It
dropped tables
.It
dropped table columns
.El
.\" The following requests should be uncommented and used where appropriate.
.\" .Sh CONTEXT
.\" For section 9 functions only.
.\" .Sh RETURN VALUES
.\" For sections 2, 3, and 9 function return values only.
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.\" .Sh FILES
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Let an existing configuration,
.Pa old.kwbp ,
consist of a
.Dq client
structure.
.Bd -literal
struct client {
  field name text limit gt 0;
  field id int rowid;
};
.Ed
.Pp
A new configuration,
.Pa new.kwbp ,
augments this structure by adding a new field, and also adds a structure.
.Bd -literal
struct client {
  field name text limit gt 0;
  field dob epoch;
  field id int rowid;
};
struct admin {
  field name text limit gt 0;
  field id int rowid;
};
.Ed
.Pp
This generates the following update script.
.Bd -literal
% ort-sqldiff old.kwbp new.kwbp
PRAGMA foreign_keys=ON;
CREATE TABLE admin (
  name TEXT NOT NULL,
  id INTEGER PRIMARY KEY
);
ALTER TABLE client ADD COLUMN dob INTEGER NOT NULL DEFAULT 0;
.Ed
.Pp
Since edit scripts are always non-destructive unless
.Fl d
was specified, the results may be piped directly into the database.
.Bd -literal
% ort-sqldiff old.kwbp new.kwbp | sqlite3 foo.db
.Ed
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr ort-sql 1 ,
.Xr sqlite3 1 ,
.Xr ort 5
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" .Sh AUTHORS
.\" .Sh CAVEATS
.\" .Sh BUGS
