name: Regression Tests
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y bmake libxml2-utils python3-jsonschema
    - name: Configure
      run: |
        cat /etc/os-release
        ./configure
        npm install
        echo "TS_NODE = node_modules/.bin/ts-node" >>Makefile.local
        echo "TS_JSONSCHEMA = node_modules/.bin/typescript-json-schema" >> Makefile.local
        echo "JSONSCHEMA = jsonschema" >> Makefile.local
        echo "XMLLINT = xmllint" >> Makefile.local
    - name: Build and test
      run: bmake regress
